export const STRING = {
  BLANK: "",
};

export const MENU_OPTS = {
  DASHBOARD: "Dashboard",
  INTENTED_IMPORT: "Intented Import",
  REQUEST_IMPORT: "Request Import",
  DECIDE_IMPORT: "Decide Import",
  HISTORY_IMPORT: "History Import",
  TRANSACTION_INVOICE_IMPORT: "Transaction Invoice",
  IMPORT: "Import",
  HANDLE_IMPORT: "Handle Import",
  ERROR_GOODS_LIST: "Errors Goods List",
  IMPORT_GOODS_LIST: "Import Goods List",
  INTENTED_EXPORT: "Intented Export",
  PURCHASE_ORDER_LIST: "Purchase Order List",
  CREATE_PURCHASE_ORDER: "Create Purchase Order",
  INVENTORY: "Inventory",
  INVENTORT_LIST: "Inventory List",
  CREATE_REQUEST: "Create Request",
  MANAGEMENT: "Management",
  GOODS: "Goods",
  PROVIDER: "Provider",
  CATEGORY: "Category",
  VOUCHER: "Voucher",
  STORAGE: "Storage",
};

export const IDX_MENU_OPTS = {
  IDX_DASHBOARD: "😳",
  IDX_INTENTED_IMPORT: "1_0",
  IDX_REQUEST_IMPORT: "1_1",
  IDX_DECIDE_IMPORT: "1_2",
  IDX_HISTORY_IMPORT: "1_3",
  IDX_TRANSACTION_INVOICE_IMPORT: "1_4",
  IDX_IMPORT: "2_0",
  IDX_HANDLE_IMPORT: "2_1",
  IDX_ERROR_GOODS_LIST: "2_2",
  IDX_IMPORT_GOODS_LIST: "2_3",
  IDX_INTENTED_EXPORT: "3_0",
  IDX_PURCHASE_ORDER_LIST: "3_1",
  IDX_CREATE_PURCHASE_ORDER: "3_2",
  IDX_INVENTORY: "4_0",
  IDX_INVENTORT_LIST: "4_1",
  IDX_CREATE_REQUEST: "4_2",
  IDX_MANAGEMENT: "5_0",
  IDX_GOODS: "5_1",
  IDX_PROVIDER: "5_2",
  IDX_CATEGORY: "5_3",
  IDX_VOUCHER: "5_4",
  IDX_STORAGE: "5_5",
};
